### ISSUE TITLE
Unraid Docker DB corruption

### ISSUE THREAD

**Issue by Hiren-Z** [Pe46dro/XBackBone-docker#13]
After updating to the Most recent "Latest" docker build I am getting http 500 erros.  After checking the logs I discovered the following error:

[2020-04-14 22:33:39] app.ERROR: Slim Application Error
Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1 no such column: current_disk_quota
File: /app/app/Database/DB.php
Line: 35
Trace: #0 /app/app/Database/DB.php(35): PDO->prepare('SELECT `id`, `e...')
#1 /app/app/Controllers/Auth/LoginController.php(51): App\Database\DB->query('SELECT `id`, `e...', Array)
#2 [internal function]: App\Controllers\Auth\LoginController->login(Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response))
#3 /app/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Array, Array)
#4 /app/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call(Array, Array)
#5 /app/vendor/slim/slim/Slim/Routing/Route.php(381): DI\Bridge\Slim\ControllerInvoker->__invoke(Array, Object(GuzzleHttp\Psr7\ServerRequest), Object(GuzzleHttp\Psr7\Response), Array)
#6 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#7 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#8 /app/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#9 /app/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(GuzzleHttp\Psr7\ServerRequest))
#10 /app/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#11 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(245): App\Middleware\InjectMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#12 /app/app/Middleware/LangMiddleware.php(25): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#13 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(245): App\Middleware\LangMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#14 /app/app/Middleware/RememberMiddleware.php(38): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#15 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(245): App\Middleware\RememberMiddleware->__invoke(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#16 /app/bootstrap/app.php(105): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#17 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): Closure->{closure}(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#18 /app/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(60): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#19 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#20 /app/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(98): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#21 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(GuzzleHttp\Psr7\ServerRequest), Object(class@anonymous))
#22 /app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#23 /app/vendor/slim/slim/Slim/App.php(211): Slim\MiddlewareDispatcher->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#24 /app/vendor/slim/slim/Slim/App.php(195): Slim\App->handle(Object(GuzzleHttp\Psr7\ServerRequest))
#25 /app/index.php(10): Slim\App->run()
#26 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []

I have had this happen in the past and the only way to correct it was to rebuild the database.  I would like to avoid that if possible this time.

**Comment by Hiren-Z** [comment]
Found a fix.

Checked the history for the readme.md and found the previous "Latest" build.
Rolled the container back to 3.0.2 by manually assigning a tag.
I was able to update to login and update to 3.1.4 through the web app
Set the container back to Latest
Now everything works fine.

**Comment by tronyx** [comment]
Did you just use the :3.0.2 tag? I've tried that and still get 500 errors.

**Comment by Hiren-Z** [comment]
Yes, I just tagged the 3.0.2 build.  However you may want to go back a few versions maybe try with 2.6.5?

**Comment by tronyx** [comment]
Same issue. Looks like I'm starting from scratch.

**Comment by tronyx** [comment]
Ok, so I stopped the container, did a full docker system prune so it would cleanup anything from the old container, and then recreated it with the hash from the previous image:

pe46dro/xbackbone-docker@sha256:7fa591004f59c0b6da5f8dc04b058aa8508adece6ee97fed2debf3573260ccd1

Now it's working.

**Comment by Pe46dro** [comment]
I have to made some tests because there is a small possibility (not too small) that i fucked up something with Docker tags

**Comment by Pe46dro** [comment]
Docker tag  `3.1`/`3.1.4` is rebuilding and should fix upgrade issues of previous versions.
I will close the issue feel free to reopen the issue.

**Comment by tronyx** [comment]
That didn't work for me. It won't even run now. Following message is spamming the container log:

```
-> Executing /opt/docker/provision/entrypoint.d/01-app.sh
mv: can't rename '/app/config.example.php': No such file or directory
-> Executing /opt/docker/provision/entrypoint.d/01-app.sh
mv: can't rename '/app/config.example.php': No such file or directory
-> Executing /opt/docker/provision/entrypoint.d/01-app.sh
mv: can't rename '/app/config.example.php': No such file or directory
-> Executing /opt/docker/provision/entrypoint.d/01-app.sh
mv: can't rename '/app/config.example.php': No such file or directory
-> Executing /opt/docker/provision/entrypoint.d/01-app.sh
mv: can't rename '/app/config.example.php': No such file or directory
```
