### ISSUE TITLE
Feature Request: MySQL as Database Backend.

### ISSUE THREAD

**Issue by CookieCr2nk** [Pe46dro/XBackBone-docker#15]
Hello,

I am running XBackbone in a Docker container. I want to ask, if you can implement environment variables for the mySQL backend?

**Comment by Pe46dro** [comment]
I will try to release a test next days

**Comment by Pe46dro** [comment]
Test available in fb6fb32 via docker-compose
I already test it on DO and via Travis but can i also ask you a feedback?

**Comment by CookieCr2nk** [comment]
Sounds good. But i use Xbackbone with traefik and a mariadb-cluster. Can you also integrate a Environment for external mariadb-servers?

**Comment by Pe46dro** [comment]
Are you running k8s?
How do you currently link traefik and my container?
Can you explain me your current infrastructure?

**Comment by CookieCr2nk** [comment]
I am running Docker.
I have create 2 static networks; traefik-web and mysql-cluster. I attached the containers to the network and use the hostname for the mysql host. Because these networks are external i don't link these containers with the link variable in docker-compose.

Mysql-Cluster: https://github.com/bitnami/bitnami-docker-mariadb-galera
Traefik: https://containo.us/traefik/

**Comment by Pe46dro** [comment]
I think you should edit `docker-compose.yml` and change the network `frontend/backend` with your static one, then you should change `configure.sh`  on line 24 to match your DB container name

**Comment by CookieCr2nk** [comment]
The MySQL Host is hardcoded. It makes more sense for me, when you make a environment variable (MYSQL_HOST) in xbb.env. So that you can Pull it to Docker Hub.
