### ISSUE TITLE
Unable to change uploud_max_filesize

### ISSUE THREAD

**Issue by DeStilleGast** [Pe46dro/XBackBone-docker#20]
So im pretty new in docker stuff and wanted to try thing thing out, after a slow start (in my opinion is it slow starting) showed in the config that the current upload limit is 50mb
![image](https://user-images.githubusercontent.com/3677706/82596829-499c1c00-9ba8-11ea-879e-78032494f87b.png)

but I want a bit more, as example 200mb, looked in the docs and there are 2 ways of doing it (?)
one is with editing the `php.ini` file, has no effect and one with adding a enviorment variable (using portainer):
![image](https://user-images.githubusercontent.com/3677706/82597003-94b62f00-9ba8-11ea-8764-b02e9f5c1c32.png)

but the webapp never starts up with this in the logs:
![image](https://user-images.githubusercontent.com/3677706/82597571-743aa480-9ba9-11ea-8d33-1605fbefc5a0.png)

what am I doing wrong ?

**Comment by Pe46dro** [comment]
Container slowness maybe is related to your setup i don't find any issue regarding speed problems.

To change max upload size you should use the ENV variable in your docker command like following:
```docker run [...]-e PHP_UPLOAD_MAX_FILESIZE=1G [...] pe46dro/xbackbone-docker```

Changes to `php.ini` inside container will be discarded on rebuild and require service restart, this type of changes are not recommended.

**Comment by DeStilleGast** [comment]
I was not here to compain about the slow start speed, but it seems like copy pasting your argument seems to work for me
