### ISSUE TITLE
Using a non-default UID

### ISSUE THREAD

**Issue by addbee** [Pe46dro/XBackBone-docker#21]
I'm using this in ansible with a unionfs directory that has fixed user/group permissions (remote storage) - there are problems when overriding the "application" UID using the CONTAINER_UID env variable which should be usable, from the parent docker image.

This suggested fix should allow file permissions matching the running user on the host, but the configure.sh is hardcoded with 1000:1000.

something along the lines of the below, replacing the end of configure.sh should use the env variable set by the parent docker image webdevops/php-nginx, and will allow users to set $CONTAINER_UID to override with their own 

There may be other references to 1000 in the tests and setup, so I've only changed locally and built the image for myself to trial

````
if [ ! -f /app/storage/.installed ]; then
	su -c "php /app/bin/migrate --install" $CONTAINER_UID
	su -c "php /app/bin/migrate" $CONTAINER_UID
	su -c "php /app/bin/clean" $CONTAINER_UID
	echo '-' > /app/storage/.installed
else
	su -c "php /app/bin/migrate" $CONTAINER_UID
        su -c "php /app/bin/clean" $CONTAINER_UID
fi

chown -R $CONTAINER_UID /app

**Comment by Pe46dro** [comment]
Thanks for the suggestion i have implemented it in 42a5f72
