### ISSUE TITLE
Uncaught PDOException after upgrade

### ISSUE THREAD

**Issue by Schmandre** [Pe46dro/XBackBone-docker#22]
I've been using docker image for a long time and after a while I wanted to upgrade to the lastest available docker version of the container. Since I upgraded, I keep getting the following error and the container does not come back online.

`Fetch the logs of a container
root@web:/home/docker/sharex# docker logs -f sharex
-> Executing /opt/docker/provision/entrypoint.d/01-app.sh
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.username in /app/app/Database/DB.php:41
Stack trace:
#0 /app/app/Database/DB.php(41): PDOStatement->execute()
#1 /app/bin/migrate(36): App\Database\DB->query(Object(PDOStatement), Array)
#2 {main}
  thrown in /app/app/Database/DB.php on line 41
`

Is there any idea, how I can fix this?

**Comment by Pe46dro** [comment]
Could you please try to run the following command:
echo '-' > YOUR_STORAGE_VOLUME/storage/.installed

**Comment by ranasats** [comment]
I had a similar issue, following the 

`echo '-' > YOUR_STORAGE_VOLUME/storage/.installed`

command fixed this. Thanks!
