### ISSUE TITLE
Unable to increase upload limit

### ISSUE THREAD

**Issue by ChloeFace** [Pe46dro/XBackBone-docker#26]
Hi I am using your docker container image, and I can't seem to increase the upload limit. I have set the environment variables when launching, as well as modified the nginx and php config files inside the container.. please help :(

**Comment by Pe46dro** [comment]
You should not modify the config file manually, you must use the env variable to change that parameter.
The upload limit is tested in the CI and it work fine, could you please post a pic of this part of the admin panel?

![image](https://user-images.githubusercontent.com/6197075/110705830-3d488480-81f7-11eb-84b4-63ad34950bf8.png)
