### ISSUE TITLE
New Xbackbone needs higher PHP version

### ISSUE THREAD

**Issue by Th3LaughingMan** [Pe46dro/XBackBone-docker#38]
Version 3.6.0 removed support for php 7.2, so currently you can't perform an upgrade within the image itself

**Comment by Freekers** [comment]
Looks like this image is no longer maintained. I suggest switching to the docker image of LinuxServer.io:  https://github.com/linuxserver/docker-xbackbone

Note: The file structure of LinuxServer.io's image is a bit different from the image of Pe46dro. Here is what I did to migrate from Pe46dro's image to LinuxServer.io's image:

1. Stop the xbackbone container running Pe46dro's image
2. Create new volumes/volume mounts for the LS.io image. 
Optional: create a new database instance for LS.io image in case you are not using the built-in SQLite DB. Do not (yet) re-use the database you're using for Pe46dro's image.
3. Spin up LS.io image as you would normally do for a new image, using the volumes/volume mounts (and optionally new database instance) you created in step 2. above
4. Complete the initial setup wizard of the LS.io image. 
Make sure to enter the correct URL for your instance and that the DB engine matches your current setup. 
Password and email address can be anything, they will be overwritten with what you have currently use as we will be restoring the database afterwards.
5. Once initial setup is complete, you will be greeted by the login screen. Now stop and remove the LS.io container
6. Copy folder and subfolders `pe46dro/storage --> ls.io/www/xbackbone/storage`
7. If you're using the builtin SQLite DB, copy folder  `pe46dro/database --> ls.io/www/xbackbone/resources/database `
If you're using an external DB, map the volumes/volume mount of your database instance to the database instance you were previously using for Pe46dro image.
8. Recreate the LS.io container. Done!

**Comment by Pe46dro** [comment]
New release is available
