### ISSUE TITLE
Preview size limited

### ISSUE THREAD

**Issue by BadSpider1** [Pe46dro/XBackBone-docker#43]
![614A32DB-552E-46F5-90E6-2A4A1D58E109](https://github.com/Pe46dro/XBackBone-docker/assets/90472078/bad33cad-6739-4093-811f-c1b09256a203)
![6D542019-739C-44F4-8CC3-07D06FF3A21F](https://github.com/Pe46dro/XBackBone-docker/assets/90472078/05e1613d-447c-4751-8b76-cd0c01048d12)

**Comment by Pe46dro** [comment]
I don't think this is a problem with docker image but with [xBackBone](https://github.com/SergiX44/xbackbone)
