### ISSUE TITLE
Increase file size upload? 

### ISSUE THREAD

**Issue by qhrizz** [Pe46dro/XBackBone-docker#7]
Hi! Found this project on reddit. Looks great and so for the testing has been positive so thank you! =)

Im just wondering if it is possible to increase the upload limit?  50M is a bit too small for me. 
Perhaps we can pass the limit in as an environment variable?

docker-compose.yaml
stuff n thing
environment:
 - post_max_size: 1G
 - upload_max_filesize: 1G

//qhrizz

**Comment by Pe46dro** [comment]
I have just added more details on [README.md](https://github.com/Pe46dro/XBackBone-docker/blob/master/README.md#php-customization)

**Comment by qhrizz** [comment]
Hi! I tried the new env variables, my docker-compose looks like: 

version: '3'
services:
  xbackbone:
    image: pe46dro/xbackbone-docker:latest
    container_name: xbackbone
    restart: always
    ports:
      - 8092:80
    environment:
     TZ: "Europe/Stockholm"
     URL: https:\/\/domain.com
     GUID: 1000
     PHP_POST_MAX_SIZE: 4G
     PHP_UPLOAD_MAX_FILESIZE: 4G
     PHP_MEMORY_LIMIT: 1024M
    volumes:
     - ./storage:/app/storage
     - ./database:/app/resources/database
     - ./logs:/app/logs

And it successfully changes the text when logging in:
![image](https://user-images.githubusercontent.com/3891378/65816983-5b3c4800-e202-11e9-864e-a1152ef70ec4.png)


but it keeps failing when I try to upload a  ~200MB file 

127.0.0.1 - - [28/Sep/2019:15:08:48 +0200] "GET /static/fontawesome/webfonts/fa-brands-400.woff2 HTTP/1.0" 200 74524 "https://domain.com/static/fontawesome/css/all.min.css?1568758454" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
2019/09/28 15:09:03 [error] 56#56: *23 client intended to send too large body: 253824667 bytes, client: 127.0.0.1, server: _, request: "POST /upload HTTP/1.0", host: "domain.com"
127.0.0.1 - - [28/Sep/2019:15:09:03 +0200] "POST /upload HTTP/1.0" 413 199 "-" "ShareX/13.0.1"
2019/09/28 15:09:06 [error] 56#56: *24 client intended to send too large body: 253824667 bytes, client: 127.0.0.1, server: _, request: "POST /upload HTTP/1.0", host: "domain.com"
127.0.0.1 - - [28/Sep/2019:15:09:06 +0200] "POST /upload HTTP/1.0" 413 199 "-" "ShareX/13.0.1"


Stack trace from shareX

Error message:
The remote server returned an error: (413) Request Entity Too Large.

Request URL:
https://domain.com/upload

Status code:
(413) Request Entity Too Large

Headers:
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains,max-age=63072000; includeSubDomains; preload
Content-Length: 199
Content-Type: text/html; charset=utf-8
Date: Sat, 28 Sep 2019 13:09:06 GMT
Server: nginx/1.14.2

Response text:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)


Any ideas? 


//qhrizz

**Comment by Pe46dro** [comment]
It's an error on nginx configuration, i will fix in next days

**Comment by AG75** [comment]
> 
> 
> It's an error on nginx configuration, i will fix in next days

if you could to add server_tokens off; i would be grateful

**Comment by Schmandre** [comment]
Hello togehter,

any updates here? 

Best regards
Schmand ;)

**Comment by Pe46dro** [comment]
I'm working about it in #10 i only have to add better travis tests and i will release in max 2 days.

**Comment by Schmandre** [comment]
Will you push this to master until finished?

**Comment by Pe46dro** [comment]
Yes
