### ISSUE TITLE
config.php and install directory in /app gets overwritten/recreated each pull

### ISSUE THREAD

**Issue by nameproof** [Pe46dro/XBackBone-docker#8]
They reside in /app which is not an available mount point.

If you could make /app available as mount point instead of
    /app/storage
    /app/resources/database
    /app/logs
it would make them persist over new pulls. Or move them from /app to somewhere you see fit as a new mount point.

The install dir is an easy fix with a 403 but I don't know how I can fix the config.php getting overwritten.

**Comment by Pe46dro** [comment]
I'll investigate in next days

**Comment by Pe46dro** [comment]
I remember that '/app' as volume generate problems btw i added it to available mount point test and let me know

**Comment by nameproof** [comment]
I tried pulling a fresh image with '/app' mounted instead of the usual ones and it's not doing what's expected. 

The host path '/app' is pointed to only contains three folders after a pull; 'logs', 'resouces' and 'storage'. 
I don't know why the rest isn't populated but it's out of my docker knowledge so I'll have to leave it here. The config.ini could be handled with variables anyway and maybe a warning about blocking the install dir could be in order as a workaround. 

Thanks for some great software
